//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15
//!  sea-orm-cli generate entity -o entity/src -u "sqlite:./mes-extra.db?mode=rwc" -t table_name

pub mod connection_config;
pub mod sync_table_columns_info;
pub mod sync_tables;
