//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sync_tables")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub sync_no: String,
    pub sync_version: String,
    pub table_name: String,
    pub is_exportable: Option<bool>,
    pub fk_columns_id: Option<i32>,
    pub created_at: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::sync_table_columns_info::Entity",
        from = "Column::FkColumnsId",
        to = "super::sync_table_columns_info::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SyncTableColumnsInfo,
}

impl Related<super::sync_table_columns_info::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SyncTableColumnsInfo.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
